"""post add category summary

Revision ID: 832b38cb577d
Revises: 9cb25cda9e93
Create Date: 2019-01-19 19:08:09.588246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '832b38cb577d'
down_revision = '9cb25cda9e93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('posts', sa.Column('category_id', sa.Integer(), nullable=True))
    op.add_column('posts', sa.Column('summary', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'posts', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'summary')
    op.drop_column('posts', 'category_id')
    op.drop_table('categories')
    # ### end Alembic commands ###
